- courses/03-cartodbjs-ground-up/lesson-1.md
changed link to go to repo instead of viewing blank html file
hey @matallo , could you double check this please :)
> changed link

- courses/03-cartodbjs-ground-up/lesson-1.md
> fixing typos, adding links to API methods

- courses/03-cartodbjs-ground-up/lesson-2.md
here's another @matallo 
thanks!!
> change viz.json to documentation account

- CONTRIBUTING.md
hey @auremoser adding this here. wanna take a look?
> Modifying contributing

- courses/04-sql-postgis/lesson-2.md
hey @matallo , could you do a merge please?
> Added information about customizing hover window

- courses/04-sql-postgis/lesson-1.md
Hi @matallo !
Would you mind merging/working magic, please?
Thank you so much.
Brittany
> minor editsBM

- _layouts/about.html
- _layouts/course.html
- _layouts/default.html
- _layouts/lesson.html
after spotting https://github.com/CartoDB/cartodb.js/issues/341
/cc @ohasselblad
> push cartodb.js version

- courses/02-design-for-beginners.md
- index.html
hey @matallo 
I just made a few minor edits to grammar, etc. with @brittanymicek
> Small updates to formatting

- _layouts/lesson.html
- courses/04-sql-postgis/lesson-1.md
Hey @matallo ,
We were talking about adding this info to the footer. What do you think? I altered the CSS directly there, but obviously you're way better at it than me and will put it in another file.
We would also like to make the line commented on below to be templated to something like this: {{page.lesson_message}} so that we can add `lesson_message` to the metadata.
> Added footer content

- courses/04-sql-postgis/lesson-1.md
just some minor fixes for this lesson
> Clarified directions

- _config.yml
- _includes/footer_scripts.html
- _layouts/about.html
- _layouts/course.html
- _layouts/default.html
- _layouts/lesson.html
> replace mixpanel => hubspot, close #128

- js/lesson.js
@matallo removes vis elements from banner
> updated createvis settings

- courses/02-design-for-beginners/lesson-3.md
> added comp op

- courses/02-design-for-beginners/lesson-4.md
> changes visualization wording

- courses/02-design-for-beginners/lesson-4.md
@iriberri this is from last week's google doc that u & andrew saw: https://docs.google.com/a/cartodb.com/document/d/10WCzucZSCpmglhUF8WIU79Jo0eXJ5jcuHfxCxr4Vns4/edit?usp=sharing
cc @ohasselblad
> Thinking About Labels: added typography resources

- courses/03-cartodbjs-ground-up/lesson-1.md
- courses/03-cartodbjs-ground-up/lesson-3.md
- t/03-cartodbjs-ground-up/lesson-1/CartoDB-js-lesson1-template.html
- t/03-cartodbjs-ground-up/lesson-1/jsfiddle_demo/demo.details
- t/03-cartodbjs-ground-up/lesson-2/CartoDB-js-lesson2-layercontrols.html
- t/03-cartodbjs-ground-up/lesson-2/CartoDB-js-lesson2-multilayer.html
- t/03-cartodbjs-ground-up/lesson-2/CartoDB-js-lesson2-ondone.html
- t/03-cartodbjs-ground-up/lesson-2/CartoDB-js-lesson2-template.html
- t/03-cartodbjs-ground-up/lesson-2/CartoDB-js-lesson2-toggles-and-slider.html
- t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_layercontrols/demo.details
- t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_multilayer/demo.details
- t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_ondone/demo.details
- t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_toggles_and_slider/demo.details
- t/03-cartodbjs-ground-up/lesson-3/CartoDB-js-lesson3-template.html
- t/03-cartodbjs-ground-up/lesson-3/cartocss-and-sql.html
- t/03-cartodbjs-ground-up/lesson-3/cartocss-string.html
- t/03-cartodbjs-ground-up/lesson-3/cartocss-style.html
- t/03-cartodbjs-ground-up/lesson-3/jsfiddle_demo_cartocss/demo.details
- t/03-cartodbjs-ground-up/lesson-3/jsfiddle_demo_cartocss_sql/demo.details
- t/03-cartodbjs-ground-up/lesson-4/bonus.html
- t/03-cartodbjs-ground-up/lesson-4/checkpoint.html
- t/03-cartodbjs-ground-up/lesson-4/template.html
- t/03-cartodbjs-ground-up/lesson-4/torque-sql.html
@ztephm could you double check that the live versions are working here? each lesson has one to three examples that have updated libraries.
> updated cdbjs library in examples

- _layouts/course.html
> updated text on course page

- js/course.js
- js/home.js
this removes search boxes and other overlays that are in visualizations used in the design elements of the page
> removes overlays from viz.jsons

- courses/05-academy-lite.md
- courses/05-academy-lite/lesson-1.md
Fixes https://github.com/CartoDB/academy/issues/157
Hi @ohasselblad please let me know about edits!
cc: @auremoser
> Added CartoCSS lesson write-up

- courses/05-academy-lite/lesson-1.md
Added conditional styling tut link in Reference section @ohasselblad + election map tut link up already.
> Added ref link to conditional styling tut

- courses/05-academy-lite/lesson-1.md
Hi @ohasselblad - added label CartoCSS in writeup since we changed the map styling slightly from what's in video.
> added labels cartocss writeup

- courses/06-intermediate-design/lesson-1.md
> Fixed typo & added docs viz.json

- courses/06-intermediate-design/lesson-1.md
> added cartocss code snippets

- courses/03-cartodbjs-ground-up/lesson-3.md
There doesn't seem to be a `master` branch anymore. Perhaps worth re-checking if there're other broken links like this one.
cc: @matallo @ohasselblad
> Fixes link to source code in Lesson 3 of CartoDB.js course

- about.md
- courses/03-cartodbjs-ground-up/lesson-3.md
I spotted several occurences more of this happening
CR @alonsogarciapablo @ohasselblad
> replace master => gh-pages branch in lesson examples

- courses/03-cartodbjs-ground-up/lesson-1.md
- courses/03-cartodbjs-ground-up/lesson-4.md
> change master => gh-pages link

- _app/_cartodbjs-ground-up/01-createvis-vs-createlayer.md
- _app/_cartodbjs-ground-up/02-creating-basic-map-apps.md
- _app/_cartodbjs-ground-up/03-basic-interactivity.md
- _app/_cartodbjs-ground-up/04-torquejs.md
- _config.yml
> link fixes

- Gemfile
- Gemfile.lock
- Gruntfile.js
close https://github.com/CartoDB/academy/issues/242
/cc @ohasselblad @ernesmb
> fix "d" and "t" folders in academy

- _app/_intermediate-design/04-use-composite-operations.md
Got the chart format working @ohasselblad + made some description updates. Look ok?
> added chart + description updates

- _app/_academy-lite/01-cartocss.md
- _app/_cartodbjs-ground-up/03-basic-interactivity.md
- _app/_design-for-beginners/02-colors-truth-insights.md
@csobier, could you take a look to make sure i'm not missing anything and that all the links are correct?
> updating links to docs

- _app/_beginners-course/02-your-first-choropleth-map.md
- _app/_beginners-course/03-thematic-maps-with-point-data.md
- _app/_cartodbjs-ground-up/01-createvis-vs-createlayer.md
> fix broken links

- _app/_includes/navigation.html
- _app/_layouts/community.html
- _app/_layouts/lesson.html
- _app/_layouts/page.html
- _app/_scss/components/_breadcrumbs.scss
- _app/_scss/components/_buttons.scss
- _app/_scss/components/_content.scss
- _app/_scss/components/_navbar.scss
- _app/_scss/mixins/_button.scss
- _app/courses/community.md
close #273
- added a new community layout
CR @ohasselblad
> community layout

- _app/_intermediate-design/01-which-kind-of-map-should-i-make.md
@ohasselblad , your call if you want to change this, as suggested, or leave as "one-click mapping" to the blog? No worries either way.
> changed one-click mapping to analyzing your dataset and updated link

- _app/_beginners-course/01-making-your-first-map.md
- _app/_beginners-course/03-thematic-maps-with-point-data.md
- _app/_beginners-course/04-animated-maps-with-point-data.md
- _app/_beginners-course/05-multilayer-visualizations.md
- _app/_cartodbjs-ground-up/02-creating-basic-map-apps.md
- _app/_cartodbjs-ground-up/03-basic-interactivity.md
- _app/_cartodbjs-ground-up/04-torquejs.md
- _app/_intermediate-design/01-which-kind-of-map-should-i-make.md
- _app/_sql-postgis/01-intro-to-sql-and-postgis.md
- _app/_sql-postgis/02-postgis-in-cartodb.md
- _app/_sql-postgis/03-joining-tables.md
- _app/courses/beginners-course.md
For Academy issue #274 
@ohasselblad , I just did a quick skim and changed table /  table view to datasets / Data View, when applicable. I was mindful to keep the "table" terminology in the SQL section. (I also snuck in a link to the Torque.js docs from your Torque.js lesson ;-)
> changed table terminology to datasets, when applicable

- _app/_cartodbjs-and-external-apis/01-google-streetview.md
- _app/_cartodbjs-and-external-apis/02-google-driving.md
- _app/_cartodbjs-ground-up/02-creating-basic-map-apps.md
- _app/_design-for-beginners/01-getting-started.md
- _app/_design-for-beginners/02-colors-truth-insights.md
- _app/_design-for-beginners/03-invisible-and-visible-data.md
- _app/_design-for-beginners/04-placing-your-labels.md
- _app/_intermediate-design/01-which-kind-of-map-should-i-make.md
- _app/_intermediate-design/04-use-composite-operations.md
- _app/_sql-postgis/01-intro-to-sql-and-postgis.md
Fixes issue #291 .
@ohasselblad , please approve and merge if OK.
> added titles for new academy lesson pages

- _app/_includes/vendor_scripts.html
re: https://github.com/CartoDB/website/issues/2614
/cc @beloneys
> analytics: add userid

- Gruntfile.js
> restore sitemap

- _app/_sql-postgis/02-postgis-in-cartodb.md
@anniecerf, could you take a look at this to make sure all of the SQL code snippets work?
closes #320 
/cc @michellechandra
> fix references to the_geom_webmercator

- _app/t/06-intermediate-design/lesson-2/index.html
> path to slider images changed

- _app/_sql-postgis/02-postgis-in-cartodb.md
> fixing redirect link

- _app/_beginners-course/03-thematic-maps-with-point-data.md
> Fix misspelling

- _app/_cartojs-ground-up/01-createvis-vs-createlayer.md
- _app/_cartojs-ground-up/02-creating-basic-map-apps.md
- _app/_cartojs-ground-up/03-basic-interactivity.md
- _app/_cartojs-ground-up/04-torquejs.md
> fixing_links in the carto.js from the ground up lessons

- _app/_cartojs-ground-up/05-named-maps.md
All links work now!
@ohasselblad
> fixing named maps broken links

- _app/_cartojs-ground-up/04-torquejs.md
Adding next lesson link to lesson 4 - carto.js #369 
@ohasselblad
> adding permalink-next

- _app/_sql-postgis/02-postgis-in-cartodb.md
@ohasselblad 
closes issue #403
> resolving sql bug in lesson 02 - postGIS in Carto

- _app/_cartojs-and-external-apis/02-google-driving.md
Issue: https://github.com/CartoDB/website/issues/3453
Could you CR @matallo please?
> 3453 - 404 fix

- Gemfile
- Gemfile.lock
> Bump jekyll version to fix deploys

- _app/_sql-postgis/01-intro-to-sql-and-postgis.md
> Fixes for 2 404s on academy
